website/api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path('messages', views.get_messages),
    path('message/create', views.create_message),
    path('message/show/<str:id>', views.get_message),
    path('register',views.create_user),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]

website/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.all_messages, name="messages"),
    path('messages/create', views.create_message, name="create_message"),
    path('messages/update/<str:id>', views.update_message, name="update_message"),
    path('messages/delete/<str:id>', views.message_delete, name="delete_message"),
    path('messages/response/add/<str:id>', views.add_response, name="response_message"),
    path('messages/response/delete/<str:id>', views.response_delete, name="delete_response"),
    path('messages/response/update/<str:id>', views.response_update, name="update_response"),
    path('messages/<str:id>', views.show_message, name="show_message"),
    path('register', views.register_view, name="register"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),

]

website/models.py
from django.contrib.auth.models import User
from django.db import models
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Message(models.Model):
    title = models.CharField(max_length=255)
    content = models.CharField(max_length=1000)
    author = models.ForeignKey(User, null=False, on_delete=models.CASCADE, default="missing_author")
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)


class Response(models.Model):
    content = models.CharField(max_length=900)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, related_name="responses")
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False, default="missing_author")

website/forms.py
from django.contrib.auth.models import User
from django.forms import Textarea, ModelForm
from website.models import Message, Category, Response
from django import forms


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ["title", "content", "category"]
        widgets = {
            "content": Textarea(attrs={"rows": 5})
        }

    category = forms.ModelChoiceField(queryset=Category.objects.all())


class RegisterForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "password"]


class ResponseForm(ModelForm):
    class Meta:
        model = Response
        fields = ["content"]

website/api/views.py
from django.contrib.auth.models import User
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from website.api.serializers import MessageSerializer, MessageCreateSerializer, UserSerializer, UserCreateSerializer
from website.models import Message


@api_view(['GET'])
def get_messages(request):
    messages = Message.objects.all()
    serialized_messages = MessageSerializer(messages, many=True)

    return Response(serialized_messages.data, status=200)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_message(request, id):
    message = Message.objects.get(id=id)
    serialized_message = MessageSerializer(message, many=False)
    return Response(serialized_message.data, status=200)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def create_message(request):

    if request.method == 'POST':
        new_message = Message()
        new_message.author = User.objects.get(id=1)
        #category_id = request.data['category']
        #new_message.category = Category.objects.get(id=category_id)
        message = MessageCreateSerializer(data=request.data, instance=new_message)
        if message.is_valid():
            message.save()
            return Response(message.data, status=status.HTTP_201_CREATED)
    return Response("nope sorry", status=status.HTTP_400_BAD_REQUEST)


@api_view(['POST'])
def create_user(request):
    if request.method == 'POST':
        user = UserCreateSerializer(data=request.data)
        if user.is_valid():
            user.save()
            return Response(user.data.username, status=status.HTTP_201_CREATED)
    return Response("nope sorry", status=status.HTTP_400_BAD_REQUEST)

website/views.py
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from .models import Message, Response
from .forms import MessageForm, ResponseForm


def all_messages(request):
    messages = Message.objects.all()
    context = {
        "messages": messages
    }

    return render(request, "website/all.html", context)


def show_message(request, id):
    message = Message.objects.get(id=id)
    return render(request, 'website/show.html', {"message": message})


@login_required(login_url="login")
def create_message(request):
    message_form = MessageForm(request.POST or None)
    if message_form.is_valid():
        message = message_form.save(commit=False)
        message.author = request.user
        message.save()
        return redirect("messages")
    return render(request, "website/create.html", {"message_form": message_form})


@login_required(login_url="login")
def update_message(request, id):
    message = get_object_or_404(Message, id=id)
    if message.author != request.user:
        return redirect("messages")
    message_form = MessageForm(request.POST or None, instance=message)
    if message_form.is_valid():
        message = message_form.save(commit=False)
        message.save()
        return redirect("messages")
    return render(request, "website/create.html", {'message_form': message_form})


@login_required(login_url="login")
def message_delete(request, id):
    message = get_object_or_404(Message, id=id)
    if message.author != request.user:
        return redirect("messages")
    if message:
        message.delete()
    return redirect("messages")


def register_view(request):
    user_form = UserCreationForm(request.POST or None)
    if user_form.is_valid():
        user = user_form.save()
        user.save()
        return redirect("messages")
    return render(request, "website/register.html", {"user_form": user_form})


def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            return redirect("messages")

    return render(request, "website/login.html", {})


def logout_view(request):
    logout(request)
    return redirect("messages")


def add_response(request, id):
    message = get_object_or_404(Message, id=id)
    if message is None:
        redirect("messages")
    response_form = ResponseForm(request.POST or None)
    if response_form.is_valid():
        response = response_form.save(commit=False)
        response.author = request.user
        response.message = message
        response.save()
        return redirect("show_message", message.id)

    return render(request, "website/show.html", {"message": message, 'response_form': response_form})


def response_delete(request, id):
    response = get_object_or_404(Response, id=id)
    if response.author != request.user:
        return redirect("messages")
    if response:
        response.delete()
    return redirect("show_message", response.message.id)


def response_update(request, id):
    response = get_object_or_404(Response, id=id)
    if response.author != request.user:
        return redirect("messages")
    response_form = ResponseForm(request.POST or None, instance=response)
    if response_form.is_valid():
        response = response_form.save(commit=False)
        response.save()
        return redirect("show_message", response.message.id)
    return render(request, "website/updateResponse.html", {"message": response.message, 'response_form': response_form})

website/templates/website/all.html
{% extends 'website/base.html' %}

{% block content %}


    {% if user.is_authenticated %}
        <h1 style="color: white">Bonjour {{ request.user }}</h1>
   {% endif %}


    <br>
{% for message in messages %}
    <br>
    <div>
    <h2>{{ message.title }}</h2>
  <p>{{ message.content }}</p>
    {% if message.category %}
        <p>Category: {{ message.category }}</p>
    {% endif %}
  <p>Wrote by: {{ message.author.username }}</p>

<a class="btn btn-success" href="{% url 'show_message' message.id  %}">Voir</a>
                {% if message.author == request.user %}
<a class="btn btn-warning" href="{% url 'update_message' message.id  %}">Update</a>
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Supprimer</button>
    {% endif %}
    </div>
  <br>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="deleteModalLabel">Supprimer?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Voulez-vous vraiment supprimer ce message?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-light" data-bs-dismiss="modal">Fermer</button>
        <a href="{% url 'delete_message' message.id  %}" type="button" class="btn btn-outline-danger">Supprimer</a>
      </div>
    </div>
  </div>
</div>

{% endfor %}


<script>
  const myModal = document.getElementById('myModal')
const myInput = document.getElementById('myInput')

myModal.addEventListener('shown.bs.modal', () => {
  myInput.focus()
})
</script>

{% endblock %}

website/templates/website/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Projet django</title>
    {%  load static %}
    <link rel="stylesheet" href="https://bootswatch.com/5/lux/bootstrap.min.css">
    <link rel="stylesheet" href={% static "styles/main.css" %}>

</head>
<body>
<nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'messages' %}">Messages</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
      
        {% if user.is_authenticated %}
            <li class="nav-item">
          <a class="nav-link btn btn-outline-primary" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
            <li class="nav-item dropdown">
          <a class="nav-link nav-linkModified dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Connect</a>
          <div class="dropdown-menu">
          <a class="nav-link btn btn-outline-primary" href="{% url 'register' %}">Register</a>
          <a class="nav-link btn btn-outline-primary" href="{% url 'login' %}">Login</a>
          </div>
        </li>
        {% endif %}

        <li class="nav-item">
          <a class="nav-link btn btn-outline-primary" href="{% url 'create_message' %}">Create a message</a>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="search" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>



<div class="container">
    {% block content %}

{% endblock %}
</div>
</body>
<script src="{% static "js/main.js" %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</html>

website/templates/website/create.html
{% extends 'website/base.html' %}

{% block content %}

<a class="btn btn-light" href="{% url 'messages' %}">Retour</a>


<form class="form-control" method="post">{% csrf_token %}
    {{ message_form.as_p }}
    <input class="btn btn-success" type="submit" value="Submit" />
</form>


{% endblock %}

website/templates/website/login.html
{% extends 'website/base.html' %}

{% block content %}

<a class="btn btn-light" href="{% url 'messages' %}">Retour</a>


<form class="form-control" method="post">{% csrf_token %}
    <input type="text" name="username" placeholder="Utilisateur">
    <input type="password" name="password" placeholder="Mot de passe">
    <input class="btn btn-success" type="submit" value="Submit" />
</form>


{% endblock %}

website/templates/website/register.html
{% extends 'website/base.html' %}

{% block content %}

<a class="btn btn-light" href="{% url 'messages' %}">Retour</a>


<form class="form-control" method="post">{% csrf_token %}
    {{ user_form.as_p }}
    <input class="btn btn-success" type="submit" value="Submit" />
</form>
<!-- peut aussi utiliser un formulaire crée via forms.py -->

{% endblock %}

website/templates/website/show.html
{% extends 'website/base.html' %}

{% block content %}


<a class="btn btn-light" href="{% url 'messages' %}">Back</a>

  <h2>{{ message.title }}</h2>
  <p>{{ message.content }}</p>
    {% if message.category %}
        <p>Category: {{ message.category }}</p>
    {% endif %}
  <p>Wrote by: {{ message.author.username }}</p>

    <div class="border border-dark">
    {% for response in message.response_set.all %}

        <div class="border border-dark">
        <p>{{ response.author.username }} wrote : </p>
            <p><strong>{{ response.content }}</strong></p>
        {% if response.author == request.user %}
            <a class="btn btn-warning" href="{% url 'update_response' response.id  %}">Update Response</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Remove response</button>
        {% endif %}
            </div>

    {% endfor %}
    </div>


    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="deleteModalLabel">Supprimer?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Voulez-vous vraiment supprimer cette réponse?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-light" data-bs-dismiss="modal">Fermer</button>
        <a href="{% url 'delete_response' message.id  %}" type="button" class="btn btn-outline-danger">Supprimer</a>
      </div>
    </div>
  </div>
</div>


    <form action="{% url 'response_message' message.id %}" method="post" class="form-control">{% csrf_token %}
        {{ response_form.as_p }}
        <button type="submit" class="btn btn-success">respond</button>
    </form>

{% endblock %}

website/templates/website/updateResponse.html
{% extends 'website/base.html' %}

{% block content %}

<a class="btn btn-light" href="{% url 'show_message' message.id %}">Retour</a>


<form class="form-control" method="post">{% csrf_token %}
    {{ response_form.as_p }}
    <input class="btn btn-success" type="submit" value="Submit" />
</form>


{% endblock %}